name: Twitter Bot Scheduler

on:
  # This enables the workflow to be run manually from the Actions tab.
  workflow_dispatch:
  # This schedules the workflow to run every hour, on the hour.
  schedule:
    - cron: '0 * * * *'

# Add explicit permissions
permissions:
  contents: read
  actions: read

jobs:
  post-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CRON_SECRET is set
        run: |
          if [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "❌ CRON_SECRET is not set in GitHub secrets"
            exit 1
          else
            echo "✅ CRON_SECRET is configured"
          fi
      
      - name: Call API endpoint to check for scheduled post
        run: |
          echo "🕐 Current UTC time: $(date -u)"
          echo "📡 Calling auto-post API..."
          
          response=$(curl -s -w "\n%{http_code}" \
            --request GET \
            --url 'https://vin-wallpaper.vercel.app/api/cron/auto-post?secret=${{ secrets.CRON_SECRET }}')
          
          # Extract status code and body
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "📊 HTTP Status Code: $http_code"
          echo "📄 Response Body: $body"
          
          # Check if the request was successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ API call successful"
            echo "$body" | jq -r '.message // "No message"'
          else
            echo "❌ API call failed with status $http_code"
            echo "$body"
            exit 1
          fi 