name: Twitter Bot Scheduler

on:
  # This enables the workflow to be run manually from the Actions tab.
  workflow_dispatch:
  # This schedules the workflow to run every hour, on the hour.
  schedule:
    - cron: '0 * * * *'

jobs:
  post-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint to check for scheduled post
        run: |
          curl --request GET \
          --url 'https://vin-wallpaper.vercel.app/api/cron/auto-post?secret=${{ secrets.CRON_SECRET }}' \
          --fail 